export const SET_MUSIC_LIST = 'SET_MUSIC_LIST'

export const SET_SINGER = 'SET_SINGER'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

export const SET_PLAY_MODE = 'SET_PLAY_MODE'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_DISC = 'SET_DISC'

export const SET_TOP_LIST = 'SET_TOP_LIST'

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'

export const SET_PLAY_HISTORY = 'SET_PLAY_HISTORY'

export const SET_FAVORITE_LIST = 'SET_FAVORITE_LIST'

export const SET_ACTION_WEBSOCKET = 'SET_ACTION_WEBSOCKET'

export const SET_PLAY_WEBSOCKET = 'SET_PLAY_WEBSOCKET'

export const SET_INIT_PLAYER = 'SET_INIT_PLAYER'

export const SET_DEVICE_LIST = 'SET_DEVICE_LIST'

export const SET_OTHER_DEVICE_LIST = 'SET_OTHER_DEVICE_LIST'

export const SET_CURRENT_DEVICE = 'SET_CURRENT_DEVICE'

export const SET_CURSEARCH_KEYWORDS = 'SET_CURSEARCH_KEYWORDS'

export const SET_CURSELECT_CATEGORYID = 'SET_CURSELECT_CATEGORYID'

export const SET_CURSELECT_CATEGORYTITLE = 'SET_CURSELECT_CATEGORYTITLE'

export const SET_USER_CLIENTHEIGHT = 'SET_USER_CLIENTHEIGHT'

export const SET_CURRENT_TECBOOKSLABEL = 'SET_CURRENT_TECBOOKSLABEL'

export const SET_CURRENT_SEARCHINFOLABEL = 'SET_CURRENT_SEARCHINFOLABEL'

export const SET_CURRENT_RESOURCELABEL = 'SET_CURRENT_RESOURCELABEL'

export const SET_PLAY_DETAIL = 'SET_PLAY_DETAIL'
